# docker/docker-compose.yml
version: '3.8'

# Define a dedicated network for our services to ensure reliable communication
networks:
  pharma-net:
    driver: bridge

services:
  # --- Blockchain Validator Nodes ---
  node1:
    build:
      context: ../node
    container_name: node1
    hostname: node1
    volumes:
      - ../data/node1:/app/data
    environment:
      - NODE_ID=node1
      - PORT=8000
      - PEERS=http://node2:8000,http://node3:8000,http://node4:8000
    ports:
      - "8001:8000"
    networks: # Attach to our custom network
      - pharma-net

  node2:
    build:
      context: ../node
    container_name: node2
    hostname: node2
    volumes:
      - ../data/node2:/app/data
    environment:
      - NODE_ID=node2
      - PORT=8000
      - PEERS=http://node1:8000,http://node3:8000,http://node4:8000
    networks:
      - pharma-net

  node3:
    build:
      context: ../node
    container_name: node3
    hostname: node3
    volumes:
      - ../data/node3:/app/data
    environment:
      - NODE_ID=node3
      - PORT=8000
      - PEERS=http://node1:8000,http://node2:8000,http://node4:8000
    networks:
      - pharma-net

  node4:
    build:
      context: ../node
    container_name: node4
    hostname: node4
    volumes:
      - ../data/node4:/app/data
    environment:
      - NODE_ID=node4
      - PORT=8000
      - PEERS=http://node1:8000,http://node2:8000,http://node3:8000
    networks:
      - pharma-net
      
  # --- IoT Simulator ---
  simulator:
    build:
      context: ../simulator
    container_name: simulator
    hostname: simulator
    environment:
      - NODE_URL=http://node1:8000
    depends_on:
      - node1
    networks:
      - pharma-net

  # --- Web-based Explorer ---
  explorer:
    build:
      context: ../explorer
    container_name: explorer
    hostname: explorer
    ports:
      - "3001:3000"
    depends_on:
      - node1
    networks:
      - pharma-net